export const FILTER_DATA = {
    ageRange: {
      min: 18,
      max: 100,
      default: { min: 20, max: 25 },
    },
    genderOptions: ["Female", "Male", "Both"],
    zodiacSigns: [
      "Aries",
      "Taurus",
      "Gemini",
      "Cancer",
      "Leo",
      "Virgo",
      "Libra",
      "Scorpius",
      "Sagittarius",
      "Capricorn",
      "Aquarius",
      "Pisces",
    ],
    interests: [
      "Travel ✈️",
      "Cooking 🍳",
      "Hiking ⛰️",
      "Yoga 🧘‍♀️",
      "Gaming 🎮",
      "Movies 🎥",
      "Music 🎵",
      "Photography 📸",
      "Pets 🐾",
      "Painting 🎨",
      "Art 🎭",
      "Fitness 🏋️",
      "Reading 📖",
      "Dancing 💃",
      "Sports 🏀",
      "Board Games ♟️",
      "Technology 📱",
      "Fashion 👗",
      "Motorcycling 🏍️",
      "Science 🔬",
      "History 📜",
      "Nature 🍃",
      "Adventure 🧗",
      "Gardening 🌻",
      "Foodie 🍲",
      "Writing ✍️",
      "Poetry 🖋️",
      "Astronomy 🔭",
      "Sustainable Living 🌱",
      "Film Production 🎬",
      "Meditation 🧘",
      "Comedy 🎭",
      "Volunteering 🫶",
      "DIY Projects 🛠️",
      "Art History 🏛️",
      "Snowboarding 🏂",
      "Wine Tasting 🍷",
      "Collectibles 🎩",
      "Sailing ⛵",
      "Karaoke 🎤",
      "Surfing 🏄",
      "Scuba Diving 🤿",
      "Skydiving 🪂",
      "Pottery 🏺",
      "Wildlife Conservation 🐾",
      "Ghost Hunting 👻",
      "Geocaching 📍",
      "Stand-up Comedy 🎙️",
      "Motor Racing 🏎️",
      "Paranormal Investigation 🕵️‍♂️",
    ],
  };